package jetbrains.mps.lang.textGen.behavior;

/*Generated by MPS */


public class AttributedNodePart_BehaviorDescriptor extends AbstractAppendPart_BehaviorDescriptor {
  public AttributedNodePart_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.lang.textGen.structure.AttributedNodePart";
  }
}
