// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypeNode.proto

package gr.uom.java.xmi.TypeFactMiner.Models;

public final class TypeNodeOuterClass {
  private TypeNodeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TypeNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.TypeNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated string annotations = 4;</code>
     */
    java.util.List<java.lang.String>
        getAnnotationsList();
    /**
     * <code>repeated string annotations = 4;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>repeated string annotations = 4;</code>
     */
    java.lang.String getAnnotations(int index);
    /**
     * <code>repeated string annotations = 4;</code>
     */
    com.google.protobuf.ByteString
        getAnnotationsBytes(int index);

    /**
     * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
     */
    boolean hasKind();
    /**
     * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
     */
    gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind getKind();

    /**
     * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
     */
    boolean hasNamespacee();
    /**
     * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
     */
    gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace getNamespacee();
  }
  /**
   * Protobuf type {@code Models.TypeNode}
   */
  public  static final class TypeNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.TypeNode)
      TypeNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeNode.newBuilder() to construct.
    private TypeNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeNode() {
      name_ = "";
      annotations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      kind_ = 1;
      namespacee_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TypeNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind value = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                kind_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace value = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                namespacee_ = rawValue;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                annotations_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              annotations_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          annotations_ = annotations_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.internal_static_Models_TypeNode_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.internal_static_Models_TypeNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.class, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder.class);
    }

    /**
     * Protobuf enum {@code Models.TypeNode.TypeKind}
     */
    public enum TypeKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Simple = 1;</code>
       */
      Simple(1),
      /**
       * <code>Parameterized = 2;</code>
       */
      Parameterized(2),
      /**
       * <code>WildCard = 3;</code>
       */
      WildCard(3),
      /**
       * <code>Union = 4;</code>
       */
      Union(4),
      /**
       * <code>Primitive = 5;</code>
       */
      Primitive(5),
      /**
       * <code>Intersection = 6;</code>
       */
      Intersection(6),
      /**
       * <code>Array = 7;</code>
       */
      Array(7),
      ;

      /**
       * <code>Simple = 1;</code>
       */
      public static final int Simple_VALUE = 1;
      /**
       * <code>Parameterized = 2;</code>
       */
      public static final int Parameterized_VALUE = 2;
      /**
       * <code>WildCard = 3;</code>
       */
      public static final int WildCard_VALUE = 3;
      /**
       * <code>Union = 4;</code>
       */
      public static final int Union_VALUE = 4;
      /**
       * <code>Primitive = 5;</code>
       */
      public static final int Primitive_VALUE = 5;
      /**
       * <code>Intersection = 6;</code>
       */
      public static final int Intersection_VALUE = 6;
      /**
       * <code>Array = 7;</code>
       */
      public static final int Array_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeKind valueOf(int value) {
        return forNumber(value);
      }

      public static TypeKind forNumber(int value) {
        switch (value) {
          case 1: return Simple;
          case 2: return Parameterized;
          case 3: return WildCard;
          case 4: return Union;
          case 5: return Primitive;
          case 6: return Intersection;
          case 7: return Array;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TypeKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TypeKind> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TypeKind>() {
              public TypeKind findValueByNumber(int number) {
                return TypeKind.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDescriptor().getEnumTypes().get(0);
      }

      private static final TypeKind[] VALUES = values();

      public static TypeKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TypeKind(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Models.TypeNode.TypeKind)
    }

    /**
     * Protobuf enum {@code Models.TypeNode.NameSpace}
     */
    public enum NameSpace
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TypeVariable = 1;</code>
       */
      TypeVariable(1),
      /**
       * <code>Jdk = 2;</code>
       */
      Jdk(2),
      /**
       * <code>External = 3;</code>
       */
      External(3),
      /**
       * <code>Internal = 4;</code>
       */
      Internal(4),
      /**
       * <code>Prmtv = 6;</code>
       */
      Prmtv(6),
      /**
       * <code>DontKnow = 5;</code>
       */
      DontKnow(5),
      /**
       * <code>WildCrd = 7;</code>
       */
      WildCrd(7),
      ;

      /**
       * <code>TypeVariable = 1;</code>
       */
      public static final int TypeVariable_VALUE = 1;
      /**
       * <code>Jdk = 2;</code>
       */
      public static final int Jdk_VALUE = 2;
      /**
       * <code>External = 3;</code>
       */
      public static final int External_VALUE = 3;
      /**
       * <code>Internal = 4;</code>
       */
      public static final int Internal_VALUE = 4;
      /**
       * <code>Prmtv = 6;</code>
       */
      public static final int Prmtv_VALUE = 6;
      /**
       * <code>DontKnow = 5;</code>
       */
      public static final int DontKnow_VALUE = 5;
      /**
       * <code>WildCrd = 7;</code>
       */
      public static final int WildCrd_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static NameSpace valueOf(int value) {
        return forNumber(value);
      }

      public static NameSpace forNumber(int value) {
        switch (value) {
          case 1: return TypeVariable;
          case 2: return Jdk;
          case 3: return External;
          case 4: return Internal;
          case 6: return Prmtv;
          case 5: return DontKnow;
          case 7: return WildCrd;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<NameSpace>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          NameSpace> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<NameSpace>() {
              public NameSpace findValueByNumber(int number) {
                return NameSpace.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDescriptor().getEnumTypes().get(1);
      }

      private static final NameSpace[] VALUES = values();

      public static NameSpace valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private NameSpace(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Models.TypeNode.NameSpace)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList annotations_;
    /**
     * <code>repeated string annotations = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAnnotationsList() {
      return annotations_;
    }
    /**
     * <code>repeated string annotations = 4;</code>
     */
    public int getAnnotationsCount() {
      return annotations_.size();
    }
    /**
     * <code>repeated string annotations = 4;</code>
     */
    public java.lang.String getAnnotations(int index) {
      return annotations_.get(index);
    }
    /**
     * <code>repeated string annotations = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAnnotationsBytes(int index) {
      return annotations_.getByteString(index);
    }

    public static final int KIND_FIELD_NUMBER = 2;
    private int kind_;
    /**
     * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
     */
    public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind getKind() {
      gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind result = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind.valueOf(kind_);
      return result == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind.Simple : result;
    }

    public static final int NAMESPACEE_FIELD_NUMBER = 3;
    private int namespacee_;
    /**
     * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
     */
    public boolean hasNamespacee() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
     */
    public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace getNamespacee() {
      gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace result = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace.valueOf(namespacee_);
      return result == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace.TypeVariable : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, kind_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, namespacee_);
      }
      for (int i = 0; i < annotations_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, annotations_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, kind_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, namespacee_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < annotations_.size(); i++) {
          dataSize += computeStringSizeNoTag(annotations_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAnnotationsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode)) {
        return super.equals(obj);
      }
      gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode other = (gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && getAnnotationsList()
          .equals(other.getAnnotationsList());
      result = result && (hasKind() == other.hasKind());
      if (hasKind()) {
        result = result && kind_ == other.kind_;
      }
      result = result && (hasNamespacee() == other.hasNamespacee());
      if (hasNamespacee()) {
        result = result && namespacee_ == other.namespacee_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (getAnnotationsCount() > 0) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAnnotationsList().hashCode();
      }
      if (hasKind()) {
        hash = (37 * hash) + KIND_FIELD_NUMBER;
        hash = (53 * hash) + kind_;
      }
      if (hasNamespacee()) {
        hash = (37 * hash) + NAMESPACEE_FIELD_NUMBER;
        hash = (53 * hash) + namespacee_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.TypeNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.TypeNode)
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.internal_static_Models_TypeNode_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.internal_static_Models_TypeNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.class, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder.class);
      }

      // Construct using gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        annotations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        kind_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        namespacee_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.internal_static_Models_TypeNode_descriptor;
      }

      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getDefaultInstanceForType() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance();
      }

      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode build() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode buildPartial() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode result = new gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          annotations_ = annotations_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.annotations_ = annotations_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.namespacee_ = namespacee_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode) {
          return mergeFrom((gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode other) {
        if (other == gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (!other.annotations_.isEmpty()) {
          if (annotations_.isEmpty()) {
            annotations_ = other.annotations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAnnotationsIsMutable();
            annotations_.addAll(other.annotations_);
          }
          onChanged();
        }
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        if (other.hasNamespacee()) {
          setNamespacee(other.getNamespacee());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKind()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList annotations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAnnotationsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          annotations_ = new com.google.protobuf.LazyStringArrayList(annotations_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAnnotationsList() {
        return annotations_.getUnmodifiableView();
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public int getAnnotationsCount() {
        return annotations_.size();
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public java.lang.String getAnnotations(int index) {
        return annotations_.get(index);
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAnnotationsBytes(int index) {
        return annotations_.getByteString(index);
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public Builder setAnnotations(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAnnotationsIsMutable();
        annotations_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public Builder addAnnotations(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAnnotationsIsMutable();
        annotations_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public Builder addAllAnnotations(
          java.lang.Iterable<java.lang.String> values) {
        ensureAnnotationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, annotations_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public Builder clearAnnotations() {
        annotations_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string annotations = 4;</code>
       */
      public Builder addAnnotationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAnnotationsIsMutable();
        annotations_.add(value);
        onChanged();
        return this;
      }

      private int kind_ = 1;
      /**
       * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
       */
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind getKind() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind result = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind.valueOf(kind_);
        return result == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind.Simple : result;
      }
      /**
       * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
       */
      public Builder setKind(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.TypeKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Models.TypeNode.TypeKind kind = 2;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000004);
        kind_ = 1;
        onChanged();
        return this;
      }

      private int namespacee_ = 1;
      /**
       * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
       */
      public boolean hasNamespacee() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
       */
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace getNamespacee() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace result = gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace.valueOf(namespacee_);
        return result == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace.TypeVariable : result;
      }
      /**
       * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
       */
      public Builder setNamespacee(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.NameSpace value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        namespacee_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Models.TypeNode.NameSpace namespacee = 3;</code>
       */
      public Builder clearNamespacee() {
        bitField0_ = (bitField0_ & ~0x00000008);
        namespacee_ = 1;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.TypeNode)
    }

    // @@protoc_insertion_point(class_scope:Models.TypeNode)
    private static final gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode();
    }

    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TypeNode>
        PARSER = new com.google.protobuf.AbstractParser<TypeNode>() {
      public TypeNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TypeNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TypeNode> getParserForType() {
      return PARSER;
    }

    public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_TypeNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_TypeNode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TypeNode.proto\022\006Models\"\340\002\n\010TypeNode\022\014\n" +
      "\004name\030\001 \001(\t\022\023\n\013annotations\030\004 \003(\t\022\'\n\004kind" +
      "\030\002 \002(\0162\031.Models.TypeNode.TypeKind\022.\n\nnam" +
      "espacee\030\003 \001(\0162\032.Models.TypeNode.NameSpac" +
      "e\"n\n\010TypeKind\022\n\n\006Simple\020\001\022\021\n\rParameteriz" +
      "ed\020\002\022\014\n\010WildCard\020\003\022\t\n\005Union\020\004\022\r\n\tPrimiti" +
      "ve\020\005\022\020\n\014Intersection\020\006\022\t\n\005Array\020\007\"h\n\tNam" +
      "eSpace\022\020\n\014TypeVariable\020\001\022\007\n\003Jdk\020\002\022\014\n\010Ext" +
      "ernal\020\003\022\014\n\010Internal\020\004\022\t\n\005Prmtv\020\006\022\014\n\010Dont" +
      "Know\020\005\022\013\n\007WildCrd\020\007B&\n$gr.uom.java.xmi.T" +
      "ypeFactMiner.Models"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Models_TypeNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_TypeNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_TypeNode_descriptor,
        new java.lang.String[] { "Name", "Annotations", "Kind", "Namespacee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
