// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypeGraph.proto

package gr.uom.java.xmi.TypeFactMiner.Models;

public final class TypeGraphOuterClass {
  private TypeGraphOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TypeGraphOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.TypeGraph)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    boolean hasRoot();
    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getRoot();
    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder getRootOrBuilder();

    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */
    int getEdgesCount();
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */
    boolean containsEdges(
            String key);
    /**
     * Use {@link #getEdgesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, TypeGraph>
    getEdges();
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */
    java.util.Map<String, TypeGraph>
    getEdgesMap();
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrDefault(
            String key,
            gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph defaultValue);
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code Models.TypeGraph}
   */
  public  static final class TypeGraph extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.TypeGraph)
      TypeGraphOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeGraph.newBuilder() to construct.
    private TypeGraph(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeGraph() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TypeGraph();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TypeGraph(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = root_.toBuilder();
              }
              root_ = input.readMessage(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(root_);
                root_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                edges_ = com.google.protobuf.MapField.newMapField(
                    EdgesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>
              edges__ = input.readMessage(
                  EdgesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              edges_.getMutableMap().put(
                  edges__.getKey(), edges__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetEdges();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.class, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.Builder.class);
    }

    private int bitField0_;
    public static final int ROOT_FIELD_NUMBER = 1;
    private gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode root_;
    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    public boolean hasRoot() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getRoot() {
      return root_ == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance() : root_;
    }
    /**
     * <code>required .Models.TypeNode root = 1;</code>
     */
    public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder getRootOrBuilder() {
      return root_ == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance() : root_;
    }

    public static final int EDGES_FIELD_NUMBER = 2;
    private static final class EdgesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>newDefaultInstance(
                  gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_EdgesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph> edges_;
    private com.google.protobuf.MapField<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>
    internalGetEdges() {
      if (edges_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EdgesDefaultEntryHolder.defaultEntry);
      }
      return edges_;
    }

    public int getEdgesCount() {
      return internalGetEdges().getMap().size();
    }
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    public boolean containsEdges(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetEdges().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEdgesMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, TypeGraph> getEdges() {
      return getEdgesMap();
    }
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    public java.util.Map<String, TypeGraph> getEdgesMap() {
      return internalGetEdges().getMap();
    }
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrDefault(
        String key,
        gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, TypeGraph> map =
          internalGetEdges().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
     */

    public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, TypeGraph> map =
          internalGetEdges().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRoot()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRoot().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph item : getEdgesMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getRoot());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetEdges(),
          EdgesDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRoot());
      }
      for (java.util.Map.Entry<String, TypeGraph> entry
           : internalGetEdges().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>
        edges__ = EdgesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, edges__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph)) {
        return super.equals(obj);
      }
      gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph other = (gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph) obj;

      if (hasRoot() != other.hasRoot()) return false;
      if (hasRoot()) {
        if (!getRoot()
            .equals(other.getRoot())) return false;
      }
      if (!internalGetEdges().equals(
          other.internalGetEdges())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRoot()) {
        hash = (37 * hash) + ROOT_FIELD_NUMBER;
        hash = (53 * hash) + getRoot().hashCode();
      }
      if (!internalGetEdges().getMap().isEmpty()) {
        hash = (37 * hash) + EDGES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEdges().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.TypeGraph}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.TypeGraph)
        gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraphOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetEdges();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableEdges();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.class, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.Builder.class);
      }

      // Construct using gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRootFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (rootBuilder_ == null) {
          root_ = null;
        } else {
          rootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableEdges().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.internal_static_Models_TypeGraph_descriptor;
      }

      @Override
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getDefaultInstanceForType() {
        return gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.getDefaultInstance();
      }

      @Override
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph build() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph buildPartial() {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph result = new gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (rootBuilder_ == null) {
            result.root_ = root_;
          } else {
            result.root_ = rootBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        result.edges_ = internalGetEdges();
        result.edges_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph) {
          return mergeFrom((gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph other) {
        if (other == gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph.getDefaultInstance()) return this;
        if (other.hasRoot()) {
          mergeRoot(other.getRoot());
        }
        internalGetMutableEdges().mergeFrom(
            other.internalGetEdges());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasRoot()) {
          return false;
        }
        if (!getRoot().isInitialized()) {
          return false;
        }
        for (gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph item : getEdgesMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode root_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder> rootBuilder_;
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public boolean hasRoot() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode getRoot() {
        if (rootBuilder_ == null) {
          return root_ == null ? gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance() : root_;
        } else {
          return rootBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public Builder setRoot(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode value) {
        if (rootBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          root_ = value;
          onChanged();
        } else {
          rootBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public Builder setRoot(
          gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder builderForValue) {
        if (rootBuilder_ == null) {
          root_ = builderForValue.build();
          onChanged();
        } else {
          rootBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public Builder mergeRoot(gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode value) {
        if (rootBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              root_ != null &&
              root_ != gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance()) {
            root_ =
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.newBuilder(root_).mergeFrom(value).buildPartial();
          } else {
            root_ = value;
          }
          onChanged();
        } else {
          rootBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public Builder clearRoot() {
        if (rootBuilder_ == null) {
          root_ = null;
          onChanged();
        } else {
          rootBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder getRootBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRootFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      public gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder getRootOrBuilder() {
        if (rootBuilder_ != null) {
          return rootBuilder_.getMessageOrBuilder();
        } else {
          return root_ == null ?
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.getDefaultInstance() : root_;
        }
      }
      /**
       * <code>required .Models.TypeNode root = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder>
          getRootFieldBuilder() {
        if (rootBuilder_ == null) {
          rootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNode.Builder, gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.TypeNodeOrBuilder>(
                  getRoot(),
                  getParentForChildren(),
                  isClean());
          root_ = null;
        }
        return rootBuilder_;
      }

      private com.google.protobuf.MapField<
          String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph> edges_;
      private com.google.protobuf.MapField<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>
      internalGetEdges() {
        if (edges_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EdgesDefaultEntryHolder.defaultEntry);
        }
        return edges_;
      }
      private com.google.protobuf.MapField<String, gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph>
      internalGetMutableEdges() {
        onChanged();;
        if (edges_ == null) {
          edges_ = com.google.protobuf.MapField.newMapField(
              EdgesDefaultEntryHolder.defaultEntry);
        }
        if (!edges_.isMutable()) {
          edges_ = edges_.copy();
        }
        return edges_;
      }

      public int getEdgesCount() {
        return internalGetEdges().getMap().size();
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public boolean containsEdges(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetEdges().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEdgesMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, TypeGraph> getEdges() {
        return getEdgesMap();
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public java.util.Map<String, TypeGraph> getEdgesMap() {
        return internalGetEdges().getMap();
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrDefault(
          String key,
          gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, TypeGraph> map =
            internalGetEdges().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getEdgesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, TypeGraph> map =
            internalGetEdges().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEdges() {
        internalGetMutableEdges().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public Builder removeEdges(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableEdges().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, TypeGraph>
      getMutableEdges() {
        return internalGetMutableEdges().getMutableMap();
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */
      public Builder putEdges(
          String key,
          gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableEdges().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .Models.TypeGraph&gt; edges = 2;</code>
       */

      public Builder putAllEdges(
          java.util.Map<String, TypeGraph> values) {
        internalGetMutableEdges().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.TypeGraph)
    }

    // @@protoc_insertion_point(class_scope:Models.TypeGraph)
    private static final gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph();
    }

    public static gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<TypeGraph>
        PARSER = new com.google.protobuf.AbstractParser<TypeGraph>() {
      @Override
      public TypeGraph parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeGraph(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TypeGraph> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TypeGraph> getParserForType() {
      return PARSER;
    }

    @Override
    public gr.uom.java.xmi.TypeFactMiner.Models.TypeGraphOuterClass.TypeGraph getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_TypeGraph_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_TypeGraph_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_TypeGraph_EdgesEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_TypeGraph_EdgesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017TypeGraph.proto\022\006Models\032\016TypeNode.prot" +
      "o\"\231\001\n\tTypeGraph\022\036\n\004root\030\001 \002(\0132\020.Models.T" +
      "ypeNode\022+\n\005edges\030\002 \003(\0132\034.Models.TypeGrap" +
      "h.EdgesEntry\032?\n\nEdgesEntry\022\013\n\003key\030\001 \001(\t\022" +
      " \n\005value\030\002 \001(\0132\021.Models.TypeGraph:\0028\001B&\n" +
      "$gr.uom.java.xmi.TypeFactMiner.Models"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.getDescriptor(),
        });
    internal_static_Models_TypeGraph_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_TypeGraph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_TypeGraph_descriptor,
        new String[] { "Root", "Edges", });
    internal_static_Models_TypeGraph_EdgesEntry_descriptor =
      internal_static_Models_TypeGraph_descriptor.getNestedTypes().get(0);
    internal_static_Models_TypeGraph_EdgesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_TypeGraph_EdgesEntry_descriptor,
        new String[] { "Key", "Value", });
    gr.uom.java.xmi.TypeFactMiner.Models.TypeNodeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
