package br.ufmg.dcc.labsoft.refactoringanalyzer;

import org.junit.Test;

public class TestWithRealInstancesInline {

	@Test
	public void test() throws Exception {
		TestBuilder test = new TestBuilder();

		test.project("https://github.com/google/j2objc.git", "master").atCommit("8874d70a484628d1b224a3e4ab7b723aaeeaee89").contains("Inline Method protected translateType(name String, source String, assertErrors boolean) : CompilationUnit inlined to protected translateType(name String, source String) : CompilationUnit in class com.google.devtools.j2objc.GenerationTest");
		test.project("https://github.com/facebook/facebook-android-sdk.git", "master").atCommit("845ba874cc5552f4deccf7d6262d351e4bbd72e4").contains("Inline Method private notifyDeveloperError(message String) : void inlined to public logConversionPixel(pixelId String, valueOfPixel double) : void in class com.facebook.InsightsLogger");
		test.project("https://github.com/greenrobot/EventBus.git", "master").atCommit("c69f5cf6b5aacb5334f4d3b6f12b30a8a37660e0").contains("Inline Method private runThreadsMixedEventTypeAfterRegister(threadCount int) : void inlined to private runThreadsMixedEventType(threadCount int) : void in class de.greenrobot.event.test.EventBusMultithreadedTest");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public fetchIntoStrongTarget() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("8874d70a484628d1b224a3e4ab7b723aaeeaee89").notContains("Inline Method protected compileType(name String, source String, assertErrors boolean) : CompilationUnit inlined to protected compileType(name String, source String) : CompilationUnit in class com.google.devtools.j2objc.GenerationTest");
		test.project("https://github.com/perwendel/spark.git", "master").atCommit("90019e15afbb6780b59d90308265c8d64f2ffccd").contains("Inline Method private getHttpMethodString(httpRequest HttpServletRequest) : String inlined to public doFilter(servletRequest ServletRequest, servletResponse ServletResponse, chain FilterChain) : void in class spark.webserver.MatcherFilter");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("99a6af35cf539ce295375a4e081fa8ad419e40b7").notContains("Inline Method private updateLayers(pSecondsElapsed float) : void inlined to protected onManagedUpdate(pSecondsElapsed float) : void in class org.anddev.andengine.entity.scene.Scene");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("b11a53aec7bd776081fb832f59ee543a71bb8d22").contains("Inline Method private getSingleDimensionMethod(arrayType IOSTypeBinding, retainedResult boolean) : IOSMethodBinding inlined to private newSingleDimensionArrayInvocation(arrayType ITypeBinding, dimensionExpr Expression, retainedResult boolean) : MethodInvocation in class com.google.devtools.j2objc.translate.ArrayRewriter");
		test.project("https://github.com/chrisbanes/Android-PullToRefresh.git", "master").atCommit("64be8c492230987e9b6930f2510557a3190a45fd").contains("Inline Method private checkEventForInitialPull(event MotionEvent) : boolean inlined to public onTouchEvent(event MotionEvent) : boolean in class com.handmark.pulltorefresh.library.PullToRefreshBase");
		test.project("https://github.com/LMAX-Exchange/disruptor.git", "master").atCommit("9cde6e5552d6ec700513f52bf76747451cba307a").contains("Inline Method private hasAvailableCapacity(sequence long, requiredCapacity int, dependentSequences Sequence[]) : boolean inlined to public hasAvailableCapacity(requiredCapacity int) : boolean in class com.lmax.disruptor.MultiProducerSequencer");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("aeea2e2feffb0d87ccf11dc33c2882b16c4e3dc3").contains("Inline Method protected enterInternal(pIndex int, pItem T) : void inlined to public enter(pIndex int, pItem T) : void in class org.andengine.util.adt.list.ShiftQueue");
		test.project("https://github.com/openaphid/android-flip.git", "master").atCommit("53efdbc1d8a4ef819b9f7bef3116bd872a785b20").contains("Inline Method public rotateBy(delta float) : void inlined to public draw(renderer FlipRenderer, gl GL10) : void in class com.aphidmobile.flip.FlipCards");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("c5d95d645f5e8b6de911ad7e510d793cd0aeb078").notContains("Inline Method private printTypeLiteral(type ITypeBinding) : void inlined to public visit(node TypeLiteral) : boolean in class com.google.devtools.j2objc.gen.StatementGenerator");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("905bcf56f96e2339ae81d0c9159b6c28078e3189").notContains("Inline Method private rewriteStringFormat(node MethodInvocation) : boolean inlined to public visit(node MethodInvocation) : boolean in class com.google.devtools.j2objc.translate.Rewriter");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("9f730b6e306d5d0a4fb469c52756378d1e12af2b").contains("Inline Method public getStep(pIndex int) : Step inlined to public getY(pIndex int) : int in class org.anddev.andengine.util.path.Path");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public loadIntoImageViewWithPlaceHolderResource() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/alibaba/fastjson.git", "master").atCommit("89e4e0a81b48f1b65e3461f5564335fcf1f34464").contains("Inline Method public writeByteArrayBase64(bytes byte[]) : void inlined to public writeByteArray(bytes byte[]) : void in class com.alibaba.fastjson.serializer.SerializeWriter");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public whenImageViewRequestFailsCleansUpTargetMap() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("61915e73282b9b84bf9be2282487e256ed1ee69d").contains("Inline Method public unload() : void inlined to public dispose() : void in class org.andengine.opengl.vbo.VertexBufferObject");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public whenTargetRequestCompletesCleansUpTargetMap() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("98ec67389a75f87ab8d748846bc4972ff4b438af").contains("Inline Method private getLetterBounds(pCharacter char, pSize Size) : void inlined to private createLetter(pCharacter char) : Letter in class org.anddev.andengine.opengl.font.Font");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public whenFileDecoderReturnsNullDoesNotCallComplete() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("f3a10eab30eb009f94c98caa8b2561275eab4c0b").contains("Inline Method protected getInnerDeclarations(node AbstractTypeDeclaration) : Iterable<BodyDeclaration> inlined to protected printInnerDeclarations(node AbstractTypeDeclaration) : void in class com.google.devtools.j2objc.gen.ObjectiveCSourceFileGenerator");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public loadResourceIntoTarget() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/square/picasso.git", "master").atCommit("f646c9ffe5bb829327979afceea857fee15b63ea").contains("Inline Method private getInputStream(localCacheOnly boolean) : InputStream inlined to package decode(uri Uri, options PicassoBitmapOptions, retryCount int) : Bitmap in class com.squareup.picasso.NetworkBitmapHunter");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public loadFileIntoTarget() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("052bae9f040af6394a2ac80fcdfad6012fe8f145").notContains("Inline Method private printStaticVarReference(expression ASTNode, assignable boolean) : void inlined to public visit(node SimpleName) : boolean in class com.google.devtools.j2objc.gen.StatementGenerator");
		test.project("https://github.com/square/dagger.git", "master").atCommit("fafc8984e5975718e48fac0e5028b32e67399035").notContains("Inline Method private validateComplete(rootModule TypeElement) : void inlined to public process(types Set<? extends TypeElement>, env RoundEnvironment) : boolean in class dagger.internal.codegen.FullGraphProcessor");
		test.project("https://github.com/alibaba/fastjson.git", "master").atCommit("db90cf3cc738d936170cf289cfb9c0deaccadff1").contains("Inline Method public deserialze(parser DefaultJSONParser) : T inlined to public deserialze(parser DefaultJSONParser, clazz Type, fieldName Object) : T in class com.alibaba.fastjson.parser.deserializer.BooleanDeserializer");
		test.project("https://github.com/emilsjolander/StickyListHeaders.git", "master").atCommit("9150df816c0d9912dc76cde636003ee9bfd5a507").contains("Inline Method private setup(context Context) : void inlined to public StickyListHeadersCursorAdapter(context Context, c Cursor) in class com.emilsjolander.components.stickylistheaders.StickyListHeadersCursorAdapter");
		test.project("https://github.com/alibaba/fastjson.git", "master").atCommit("db90cf3cc738d936170cf289cfb9c0deaccadff1").notContains("Inline Method public deserialze(parser DefaultJSONParser) : T inlined to public deserialze(parser DefaultJSONParser, clazz Type, fieldName Object) : T in class com.alibaba.fastjson.parser.deserializer.IntegerDeserializer");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public loadIntoTarget() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/nicolasgramlich/AndEngine.git", "master").atCommit("41cbc66631600c9b28147d1424af170319f0d0e6").notContains("Inline Method private allocateChildren() : void inlined to public add(pItem T, pBoundsSource S) : void in class org.anddev.andengine.util.spatial.quadtree.QuadTree.QuadTreeNode");
		test.project("https://github.com/ACRA/acra.git", "master").atCommit("ddf33599e54c246f6547cc499daf6c10f4df3b96").contains("Inline Method private initAcra() : void inlined to public init(app Application) : void in class org.acra.ACRA");
		test.project("https://github.com/alibaba/fastjson.git", "master").atCommit("151092ebaa04f3d76fbd59deddc184867cd3e0d2").contains("Inline Method private _setContext(context Context, mw MethodVisitor, setObject boolean) : void inlined to package _deserialze(cw ClassWriter, context Context) : void in class com.alibaba.fastjson.parser.deserializer.ASMDeserializerFactory");
		test.project("https://github.com/junit-team/junit.git", "master").atCommit("85f9d8397bfd96261c3214284672180c522e2d38").contains("Inline Method private invokeValidatorsOnClass(annotation Annotation, errors List<Throwable>) : void inlined to private invokeValidatorsOnClass(errors List<Throwable>) : void in class org.junit.runners.ParentRunner");
		test.project("https://github.com/alibaba/fastjson.git", "master").atCommit("04651b91ff44900e33d1e8e31e65d9b24a394bfb").contains("Inline Method public createJavaBeanDeserializer(clazz Class<?>) : ObjectDeserializer inlined to public getDeserializer(clazz Class<?>, type Type) : ObjectDeserializer in class com.alibaba.fastjson.parser.ParserConfig");
		test.project("https://github.com/square/picasso.git", "master").atCommit("65cf422a7b0d3e5434ffe9c068408fecc4d9e05c").contains("Inline Method private assertMapsAreEmpty(picasso Picasso) : void inlined to public whenDecoderReturnsNullDoesNotCallComplete() : void in class com.squareup.picasso.PicassoTest");
		test.project("https://github.com/square/picasso.git", "master").atCommit("d88531e67a1fcbfbbf33c2973d4a2dff2018bbef").contains("Inline Method private mockMeOneNow(service ExecutorService) : Dispatcher inlined to public performNetworkStateChangeWithConnectedInfoAndPicassoExecutorServiceAdjustsThreads() : void in class com.squareup.picasso.DispatcherTest");
		test.project("https://github.com/google/j2objc.git", "master").atCommit("9fe60735104605c3658c94a90065f995f38d52ef").contains("Inline Method private printUnsignedRightShift(lhs Expression, rhs Expression) : void inlined to public visit(node InfixExpression) : boolean in class com.google.devtools.j2objc.gen.StatementGenerator");
		test.project("https://github.com/koush/AndroidAsync.git", "master").atCommit("09c60732944a20eac52301026e9c24344ccb3062").contains("Inline Method private open() : void inlined to public addCache(client AsyncHttpClient, cacheDir File, size long) : ResponseCacheMiddleware in class com.koushikdutta.async.http.ResponseCacheMiddleware");
		test.project("https://github.com/LMAX-Exchange/disruptor.git", "master").atCommit("c6d74ced692feb3e154335b60ee5cff6bd7d5761").contains("Inline Method private checkAndIncrement(requiredCapacity int, delta int, dependentSequences Sequence[]) : long inlined to public tryNext(requiredCapacity int) : long in class com.lmax.disruptor.MultiProducerSequencer");
		test.project("https://github.com/WhisperSystems/TextSecure.git", "master").atCommit("7c9282f3067b436ac58daa748c23b9732af2d36f").contains("Inline Method public buildPartial() : PushMessageContent inlined to public mergeFrom(input CodedInputStream, extensionRegistry ExtensionRegistryLite) : Builder in class org.whispersystems.textsecure.push.GroupContext.Builder");
		test.project("https://github.com/WhisperSystems/TextSecure.git", "master").atCommit("3dd27ed59a8fb686f50609ec4fef898ef4ff098f").notContains("Inline Method public buildPartial() : PushMessageContent inlined to public mergeFrom(input CodedInputStream, extensionRegistry ExtensionRegistryLite) : Builder in class org.whispersystems.textsecure.push.GroupContext.Builder");
		test.project("https://github.com/WhisperSystems/TextSecure.git", "master").atCommit("5a3daf48469c336405e88843488d52f24311a862").notContains("Inline Method public mergeFrom(other PushMessageContent) : Builder inlined to public mergeFrom(input CodedInputStream, extensionRegistry ExtensionRegistryLite) : Builder in class org.whispersystems.textsecure.push.GroupContext.Builder");
		test.project("https://github.com/square/okhttp.git", "master").atCommit("fee27209135228900cea58e78b71fbc4fdd7792c").notContains("Inline Method package cipherSuites(cipherSuites String[]) : Builder inlined to public cipherSuites(cipherSuites CipherSuite) : Builder in class com.squareup.okhttp.ConnectionSpec.Builder");
		test.project("https://github.com/WhisperSystems/TextSecure.git", "master").atCommit("928b9687efe9e3c72a129ccdc0208281b725505e").notContains("Inline Method public buildPartial() : PushMessageContent inlined to public mergeFrom(input CodedInputStream, extensionRegistry ExtensionRegistryLite) : Builder in class org.whispersystems.textsecure.push.GroupContext.Builder");
		test.project("https://github.com/WhisperSystems/TextSecure.git", "master").atCommit("d1dd50e31c909943cf9bf8d94f5ab608dcda82f4").notContains("Inline Method public mergeFrom(other PushMessageContent) : Builder inlined to public mergeFrom(input CodedInputStream, extensionRegistry ExtensionRegistryLite) : Builder in class org.whispersystems.textsecure.push.GroupContext.Builder");
		test.project("https://github.com/dropwizard/metrics.git", "master").atCommit("25244eeda64c6dcdf59889a6584851a91039d8e3").contains("Inline Method public clear() : void inlined to public UniformSample(reservoirSize int) in class com.yammer.metrics.UniformSample");
		test.project("https://github.com/bumptech/glide.git", "master").atCommit("1d11261d4ec2ab97c5eec91a3d1c14625c5b23ca").contains("Inline Method private finish(target Y) : Y inlined to public into(target Y) : Y in class com.bumptech.glide.Glide.GenericRequest");

		//Precision: 0,810  Recall: 0,919
		test.assertExpectations();
	}

}
