package org.voltdb.sqlparser.symtab;

import org.assertj.core.api.AbstractAssert;
import org.voltdb.sqlparser.semantics.symtab.Type;

/**
 * {@link Type} specific assertions - Generated by CustomAssertionGenerator.
 */
public class TypeAssert extends AbstractAssert<TypeAssert, Type> {

    /**
     * Creates a new </code>{@link TypeAssert}</code> to make assertions on actual Type.
     * @param actual the Type we want to make assertions on.
     */
    public TypeAssert(Type actual) {
        super(actual, TypeAssert.class);
    }

    /**
     * An entry point for TypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
     * With a static import, one's can write directly : <code>assertThat(myType)</code> and get specific assertion with code completion.
     * @param actual the Type we want to make assertions on.
     * @return a new </code>{@link TypeAssert}</code>
     */
    public static TypeAssert assertThat(Type actual) {
        return new TypeAssert(actual);
    }

}
