package com.example.myapplication.data

import android.content.Context
import com.google.android.gms.maps.model.LatLng
import com.google.gson.Gson
import com.example.myapplication.R
import com.example.myapplication.telemetry.CrashReporter
data class JsonLatLng(val latitude: Double, val longitude: Double)

data class Building(
    val name: String,
    val code: String,
    val wayID: Long,
    val address: String,
    val outline: List<JsonLatLng>?, // Make nullable for safety
    val isCampusBuilding: Boolean = true
) {
    fun getGoogleOutline(): List<LatLng> = outline?.map { LatLng(it.latitude, it.longitude) } ?: emptyList()

    fun getCenter(): LatLng {
        val points = getGoogleOutline()
        if (points.isEmpty()) return LatLng(45.497, -73.579) // Fallback to SGW center

        val avgLat = points.map { it.latitude }.average()
        val avgLng = points.map { it.longitude }.average()
        return LatLng(avgLat, avgLng)
    }
}

data class Campus(
    val name: String,
    val center: JsonLatLng,
    val buildings: List<Building>,
    val outline: List<JsonLatLng>?, // Make nullable for safety
    val defaultZoom: Float = 17f
) {
    fun getGoogleCenter(): LatLng = LatLng(center.latitude, center.longitude)
    fun getGoogleOutline(): List<LatLng> = outline?.map { LatLng(it.latitude, it.longitude) } ?: emptyList()
}

data class CampusDataWrapper(val campuses: List<Campus>)

object CampusRepo {
    private var allCampuses: List<Campus> = emptyList()

    fun initialize(context: Context) {
        android.util.Log.d("DATA_CHECK", "1. Initialize started (using res/raw)")
        try {
            // Use the Resource ID generated by Android for the file in res/raw/campuses.json
            val inputStream = context.resources.openRawResource(R.raw.campuses)

            val jsonString = inputStream.bufferedReader().use { it.readText() }
            android.util.Log.d("DATA_CHECK", "2. JSON read success. Length: ${jsonString.length}")

            val wrapper = Gson().fromJson(jsonString, CampusDataWrapper::class.java)

            if (wrapper != null) {
                allCampuses = wrapper.campuses
                android.util.Log.d("DATA_CHECK", "3. Success! Loaded ${allCampuses.size} campuses")
            } else {
                android.util.Log.e("DATA_CHECK", "3. ERROR: Gson returned null wrapper")
            }
        } catch (e: Exception) {
            android.util.Log.e("DATA_CHECK", "FATAL ERROR: ${e.message}")
            CrashReporter.setKey("campus_data_source", "res/raw/campuses.json")
            CrashReporter.recordNonFatal(e, "campus_data_initialize_failed")
            e.printStackTrace()
        }
    }

    // This now accepts Google's LatLng so MapsActivity is happy
    fun getCampus(point: LatLng): Campus? {
        // 1. Strict Check: Is the user physically inside the campus perimeter?
        val insideCampus = allCampuses.find { campus ->
            val outline = campus.getGoogleOutline()
            outline.isNotEmpty() && isInsidePolygon(point, outline)
        }
        if (insideCampus != null) return insideCampus

        // 2. Strict Check: Is the user inside a specific building?
        val insideBuilding = allCampuses.find { campus ->
            campus.buildings.any { building ->
                isInsidePolygon(point, building.getGoogleOutline())
            }
        }
        if (insideBuilding != null) return insideBuilding

        // 3. Conditional Fallback: Only return the nearest if within a logical "Campus Zone"
        val maxDistanceDegrees = 0.005

        return allCampuses.filter { campus ->
            val center = campus.getGoogleCenter()
            val dist = Math.sqrt(Math.pow(point.latitude - center.latitude, 2.0) +
                    Math.pow(point.longitude - center.longitude, 2.0))
            dist < maxDistanceDegrees
        }.minByOrNull { campus ->
            val center = campus.getGoogleCenter()
            Math.sqrt(Math.pow(point.latitude - center.latitude, 2.0) +
                    Math.pow(point.longitude - center.longitude, 2.0))
        }
    }

    fun getCampusByName(name: String): Campus? = allCampuses.find {
        it.name.trim().equals(name.trim(), ignoreCase = true)
    }



    private fun isInsidePolygon(point: LatLng, polygon: List<LatLng>): Boolean {
        if (polygon.isEmpty()) return false
        var intersectCount = 0
        for (j in polygon.indices) {
            val i = if (j == 0) polygon.size - 1 else j - 1
            if (rayCastIntersect(point, polygon[i], polygon[j])) intersectCount++
        }
        return intersectCount % 2 != 0
    }

    fun setTestCampuses(campuses: List<Campus>) {
        allCampuses = campuses
    }
    private fun rayCastIntersect(tap: LatLng, vertA: LatLng, vertB: LatLng): Boolean {
        val aY = vertA.latitude;  val bY = vertB.latitude
        val aX = vertA.longitude; val bX = vertB.longitude
        val pY = tap.latitude;    val pX = tap.longitude

        // Skip horizontal edges — they never contribute to the crossing count.
        if (aY == bY) return false

        // Vertical edges (aX == bX) have an infinite slope in the x-from-y formula.
        // Use an epsilon-based check: if the edge is nearly vertical, test directly
        // whether the ray passes to the left of the edge's x-coordinate.
        val EPSILON = 1e-10
        if (kotlin.math.abs(aX - bX) < EPSILON) {
            // Edge is vertical — only count it if the tap is within the y-range
            // and the edge is to the right of the tap.
            val minY = minOf(aY, bY)
            val maxY = maxOf(aY, bY)
            return pY in minY..maxY && aX > pX
        }

        // Standard ray-casting: compute x-intersection of the horizontal ray
        // from tap with the infinite line through vertA–vertB.
        if ((aY > pY && bY > pY) || (aY < pY && bY < pY) || (aX < pX && bX < pX)) return false

        val m = (aY - bY) / (aX - bX)
        val bee = aY - m * aX
        val xIntersection = (pY - bee) / m
        return xIntersection > pX
    }
    fun getAllCampuses(): List<Campus> = allCampuses

    /**
     * Flat list of all buildings across all campuses.
     * Cached after first access — avoids repeated flatMap on every
     * IndoorJourneyHandler call. Data is immutable after initialize().
     */
    private var _allBuildings: List<Building>? = null
    fun getAllBuildings(): List<Building> =
        _allBuildings ?: allCampuses.flatMap { it.buildings }.also { _allBuildings = it }
}
