package gr.uom.java.xmi;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

import org.eclipse.cdt.core.dom.ast.IASTCompositeTypeSpecifier;
import org.eclipse.cdt.core.dom.ast.IASTDeclaration;
import org.eclipse.cdt.core.dom.ast.IASTDeclSpecifier;
import org.eclipse.cdt.core.dom.ast.IASTDeclarator;
import org.eclipse.cdt.core.dom.ast.IASTEnumerationSpecifier;
import org.eclipse.cdt.core.dom.ast.IASTFunctionDeclarator;
import org.eclipse.cdt.core.dom.ast.IASTFunctionDefinition;
import org.eclipse.cdt.core.dom.ast.IASTParameterDeclaration;
import org.eclipse.cdt.core.dom.ast.IASTPreprocessorIncludeStatement;
import org.eclipse.cdt.core.dom.ast.IASTSimpleDeclaration;
import org.eclipse.cdt.core.dom.ast.IASTStandardFunctionDeclarator;
import org.eclipse.cdt.core.dom.ast.IASTTranslationUnit;
import org.eclipse.cdt.core.dom.ast.IASTNode;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTCompositeTypeSpecifier;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTCompositeTypeSpecifier.ICPPASTBaseSpecifier;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTDeclSpecifier;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTFunctionDeclarator;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTNamespaceDefinition;
import org.eclipse.cdt.core.dom.ast.cpp.ICPPASTVisibilityLabel;
import org.eclipse.cdt.core.dom.ast.gnu.cpp.GPPLanguage;
import org.eclipse.cdt.core.model.ILanguage;
import org.eclipse.cdt.core.parser.DefaultLogService;
import org.eclipse.cdt.core.parser.FileContent;
import org.eclipse.cdt.core.parser.IScannerInfo;
import org.eclipse.cdt.core.parser.IncludeFileContentProvider;
import org.eclipse.cdt.core.parser.ScannerInfo;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.cdt.core.parser.IParserLogService;

import com.github.gumtreediff.gen.treesitterng.CTreeSitterNgTreeGenerator;
import com.github.gumtreediff.gen.treesitterng.CppTreeSitterNgTreeGenerator;
import com.github.gumtreediff.tree.TreeContext;

import gr.uom.java.xmi.decomposition.VariableDeclaration;

public class CppFileProcessor {
	private static final String FREE_MARKER_GENERATED = "generated using freemarker";
	private static final String FREE_MARKER_GENERATED_2 = "generated using FreeMarker";
	private static final String ANTLR_GENERATED = "// $ANTLR";
	private static final String XTEXT_GENERATED = "generated by Xtext";
	private static final String LWJGL_GENERATED = "MACHINE GENERATED FILE, DO NOT EDIT";
	private static final String TEST_GENERATOR_GENERATED = "generated by TestGenerator";
	private static final String THRIFT_GENERATED = "Autogenerated by Thrift Compiler";
	private static final String AUTOREST_GENERATED = "AutoRest Code Generator";
	private static final String FHIR_GENERATED = "for FHIR";
	private static final String CAMEL_GENERATED = "Generated by camel-package-maven-plugin";

	private UMLModel umlModel;
	private Map<String, UMLClass> cppClassMap = new LinkedHashMap<>();

	
	public CppFileProcessor(UMLModel umlModel) {
		this.umlModel = umlModel;
	}

	public void processCppFile(String filePath, String fileContent, boolean astDiff) {
		
		System.out.println("Hello from CppFileProcessor: " + filePath);
		
		if((fileContent.contains(FREE_MARKER_GENERATED) || fileContent.contains(FREE_MARKER_GENERATED_2) || fileContent.contains(ANTLR_GENERATED) ||
				fileContent.contains(XTEXT_GENERATED) || fileContent.contains(LWJGL_GENERATED) || fileContent.contains(TEST_GENERATOR_GENERATED) ||
				fileContent.contains(THRIFT_GENERATED) || fileContent.contains(AUTOREST_GENERATED) || fileContent.contains(FHIR_GENERATED) ||
				fileContent.contains(CAMEL_GENERATED)) &&
				!fileContent.contains("\"" + CAMEL_GENERATED + "\"") &&
				!fileContent.contains("private static final String FREE_MARKER_GENERATED = \"generated using freemarker\";")) {
			return;
		}
		try {
			IASTTranslationUnit translationUnit = getTranslationUnit(filePath, fileContent);
			processTranslationUnit(filePath, translationUnit, fileContent);
			if(astDiff) {
				ByteArrayInputStream is = new ByteArrayInputStream(fileContent.getBytes());
				TreeContext treeContext = filePath.endsWith(".c") ?
						new CTreeSitterNgTreeGenerator().generateFrom().stream(is) :
							new CppTreeSitterNgTreeGenerator().generateFrom().stream(is);
				this.umlModel.getTreeContextMap().put(filePath, treeContext);
			}
		}
		catch(CoreException | IOException e) {
			//e.printStackTrace();
		}
	}

	private IASTTranslationUnit getTranslationUnit(String filePath, String fileContent) throws CoreException {
		FileContent fileContentObj = FileContent.create(filePath, fileContent.toCharArray());
		IScannerInfo scannerInfo = new ScannerInfo(Map.of(), new String[0]);
		IncludeFileContentProvider includes = IncludeFileContentProvider.getEmptyFilesProvider();
		IParserLogService log = new DefaultLogService();
		return GPPLanguage.getDefault().getASTTranslationUnit(
				fileContentObj,
				scannerInfo,
				includes,
				null,
				ILanguage.OPTION_IS_SOURCE_UNIT,
				log
		);
	}

	private void processTranslationUnit(String filePath, IASTTranslationUnit translationUnit, String fileContent) {
		cppClassMap = new LinkedHashMap<>();
		for(IASTDeclaration declaration : translationUnit.getDeclarations()) {
			processDeclaration(declaration, "");
		}
		for(IASTDeclaration declaration : translationUnit.getDeclarations()) {
			processModelDeclaration(declaration, "", "", filePath, fileContent);
		}
		System.out.println("C++ UML classes added: " + cppClassMap.keySet());
		printCppUmlSummary();
		printAstSummary(filePath, translationUnit);
	}

	private void processModelDeclaration(IASTDeclaration declaration, String namespace, String sourceFolder, String filePath, String fileContent) {
		if(declaration instanceof ICPPASTNamespaceDefinition namespaceDefinition) {
			String nestedNamespace = namespace.isEmpty() ? namespaceDefinition.getName().toString() : namespace + "." + namespaceDefinition.getName().toString();
			for(IASTDeclaration nestedDeclaration : namespaceDefinition.getDeclarations()) {
				processModelDeclaration(nestedDeclaration, nestedNamespace, sourceFolder, filePath, fileContent);
			}
		}
		else if(declaration instanceof IASTSimpleDeclaration simpleDeclaration) {
			IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
			if(declSpecifier instanceof ICPPASTCompositeTypeSpecifier compositeType) {
				processCompositeType(namespace, compositeType, sourceFolder, filePath, fileContent);
			}
			else if(hasFunctionDeclarator(simpleDeclaration)) {
				processOutOfClassOperation(namespace, sourceFolder, filePath, fileContent, declSpecifier, simpleDeclaration.getDeclarators(), simpleDeclaration);
			}
			else {
				processOutOfClassAttribute(namespace, sourceFolder, filePath, fileContent, simpleDeclaration);
			}
		}
		else if(declaration instanceof IASTFunctionDefinition functionDefinition) {
			processOutOfClassOperation(namespace, sourceFolder, filePath, fileContent, functionDefinition.getDeclSpecifier(),
					new IASTDeclarator[] { functionDefinition.getDeclarator() }, functionDefinition);
		}
	}

	private void processCompositeType(String namespace, ICPPASTCompositeTypeSpecifier compositeType, String sourceFolder, String filePath, String fileContent) {
		String className = compositeType.getName().toString();
		LocationInfo locationInfo = cppLocation(sourceFolder, filePath, compositeType, LocationInfo.CodeElementType.TYPE_DECLARATION, fileContent);
		UMLClass umlClass = new UMLClass(namespace, className, locationInfo, true, new ArrayList<>());
		umlClass.setActualSignature(compositeType.getRawSignature());
		umlClass.setVisibility(Visibility.PUBLIC);
		if(compositeType.getKey() == IASTCompositeTypeSpecifier.k_struct) {
			umlClass.setVisibility(Visibility.PUBLIC);
		}
		if(compositeType.getKey() == ICPPASTCompositeTypeSpecifier.k_class) {
			umlClass.setVisibility(Visibility.PUBLIC);
		}
		cppClassMap.put(qualifiedClassName(namespace, className), umlClass);
		umlModel.addClass(umlClass);

		for(ICPPASTBaseSpecifier baseSpecifier : compositeType.getBaseSpecifiers()) {
			umlModel.addGeneralization(new UMLGeneralization(umlClass, qualifyCppName(namespace, baseSpecifier.getName().toString())));
		}

		Visibility currentVisibility = compositeType.getKey() == IASTCompositeTypeSpecifier.k_struct ? Visibility.PUBLIC : Visibility.PRIVATE;
		for(IASTDeclaration member : compositeType.getMembers()) {
			if(member instanceof ICPPASTVisibilityLabel visibilityLabel) {
				currentVisibility = visibility(visibilityLabel.getVisibility(), currentVisibility);
			}
			else if(member instanceof IASTSimpleDeclaration simpleDeclaration) {
				IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
				if(hasFunctionDeclarator(simpleDeclaration)) {
					for(IASTDeclarator declarator : simpleDeclaration.getDeclarators()) {
						if(declarator instanceof IASTFunctionDeclarator functionDeclarator) {
							UMLOperation operation = createOperation(sourceFolder, filePath, fileContent, declSpecifier, functionDeclarator, simpleDeclaration, umlClass.getName(), className, currentVisibility);
							addOrReplaceOperation(umlClass, operation);
						}
					}
				}
				else if(!(declSpecifier instanceof IASTEnumerationSpecifier) && !(declSpecifier instanceof ICPPASTCompositeTypeSpecifier)) {
					for(UMLAttribute attribute : createAttributes(sourceFolder, filePath, fileContent, simpleDeclaration, umlClass.getName(), currentVisibility)) {
						umlClass.addAttribute(attribute);
					}
				}
			}
			else if(member instanceof IASTFunctionDefinition functionDefinition) {
				UMLOperation operation = createOperation(sourceFolder, filePath, fileContent, functionDefinition.getDeclSpecifier(),
						functionDefinition.getDeclarator(), functionDefinition, umlClass.getName(), className, currentVisibility);
				addOrReplaceOperation(umlClass, operation);
			}
		}
	}

	private void processOutOfClassOperation(String namespace, String sourceFolder, String filePath, String fileContent,
			IASTDeclSpecifier declSpecifier, IASTDeclarator[] declarators, IASTNode locationNode) {
		for(IASTDeclarator declarator : declarators) {
			if(declarator instanceof IASTFunctionDeclarator functionDeclarator) {
				String name = functionName(functionDeclarator);
				String ownerName = ownerName(name);
				if(ownerName != null) {
					UMLClass ownerClass = cppClassMap.get(qualifiedClassName(namespace, ownerName));
					if(ownerClass != null) {
						UMLOperation operation = createOperation(sourceFolder, filePath, fileContent, declSpecifier, functionDeclarator, locationNode,
								ownerClass.getName(), ownerName, Visibility.PUBLIC);
						addOrReplaceOperation(ownerClass, operation);
					}
				}
			}
		}
	}

	private void processOutOfClassAttribute(String namespace, String sourceFolder, String filePath, String fileContent, IASTSimpleDeclaration simpleDeclaration) {
		for(IASTDeclarator declarator : simpleDeclaration.getDeclarators()) {
			String name = declarator.getName().toString();
			String ownerName = ownerName(name);
			if(ownerName != null) {
				UMLClass ownerClass = cppClassMap.get(qualifiedClassName(namespace, ownerName));
				if(ownerClass != null && ownerClass.getAttributes().stream().noneMatch(attribute -> attribute.getName().equals(simpleFunctionName(name)))) {
					UMLType type = UMLType.extractTypeObject(stripLeadingKeywords(oneLine(simpleDeclaration.getDeclSpecifier().getRawSignature()), modifiers(simpleDeclaration.getDeclSpecifier(), null)));
					LocationInfo location = cppLocation(sourceFolder, filePath, declarator, LocationInfo.CodeElementType.FIELD_DECLARATION, fileContent);
					UMLAttribute attribute = new UMLAttribute(simpleFunctionName(name), type, location, ownerClass.getName());
					attribute.setFieldDeclarationLocationInfo(cppLocation(sourceFolder, filePath, simpleDeclaration, LocationInfo.CodeElementType.FIELD_DECLARATION, fileContent));
					attribute.setVisibility(Visibility.PUBLIC);
					attribute.setStatic(simpleDeclaration.getDeclSpecifier().getStorageClass() == IASTDeclSpecifier.sc_static || name.contains("::"));
					attribute.setVariableDeclaration(new VariableDeclaration(sourceFolder, filePath, declarator, type, true, fileContent));
					ownerClass.addAttribute(attribute);
				}
			}
		}
	}

	private List<UMLAttribute> createAttributes(String sourceFolder, String filePath, String fileContent, IASTSimpleDeclaration simpleDeclaration,
			String className, Visibility visibility) {
		List<UMLAttribute> attributes = new ArrayList<>();
		IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
		String typeName = stripLeadingKeywords(oneLine(declSpecifier.getRawSignature()), modifiers(declSpecifier, null));
		for(IASTDeclarator declarator : simpleDeclaration.getDeclarators()) {
			String attributeName = declarator.getName().toString();
			UMLType type = UMLType.extractTypeObject(typeName);
			LocationInfo location = cppLocation(sourceFolder, filePath, declarator, LocationInfo.CodeElementType.FIELD_DECLARATION, fileContent);
			UMLAttribute attribute = new UMLAttribute(attributeName, type, location, className);
			attribute.setFieldDeclarationLocationInfo(cppLocation(sourceFolder, filePath, simpleDeclaration, LocationInfo.CodeElementType.FIELD_DECLARATION, fileContent));
			attribute.setVisibility(visibility);
			attribute.setStatic(declSpecifier.getStorageClass() == IASTDeclSpecifier.sc_static);
			attribute.setVariableDeclaration(new VariableDeclaration(sourceFolder, filePath, declarator, type, true, fileContent));
			attributes.add(attribute);
		}
		return attributes;
	}

	private UMLOperation createOperation(String sourceFolder, String filePath, String fileContent, IASTDeclSpecifier declSpecifier,
			IASTFunctionDeclarator declarator, IASTNode locationNode, String className, String simpleClassName, Visibility visibility) {
		String name = simpleFunctionName(functionName(declarator));
		LocationInfo location = cppLocation(sourceFolder, filePath, locationNode, LocationInfo.CodeElementType.METHOD_DECLARATION, fileContent);
		UMLOperation operation = new UMLOperation(name, location, className);
		operation.setActualSignature(locationNode.getRawSignature());
		operation.setVisibility(visibility);
		operation.setConstructor(name.equals(simpleClassName));
		operation.setStatic(declSpecifier.getStorageClass() == IASTDeclSpecifier.sc_static);
		if(declarator instanceof ICPPASTFunctionDeclarator cppDeclarator) {
			operation.setAbstract(cppDeclarator.isPureVirtual());
			operation.setFinal(cppDeclarator.isFinal());
		}
		addReturnParameter(operation, declSpecifier, name, simpleClassName);
		addParameters(operation, declarator, sourceFolder, filePath, fileContent);
		return operation;
	}

	private void addReturnParameter(UMLOperation operation, IASTDeclSpecifier declSpecifier, String operationName, String simpleClassName) {
		if(operationName.equals(simpleClassName) || operationName.equals("~" + simpleClassName)) {
			return;
		}
		String returnType = stripLeadingKeywords(oneLine(declSpecifier.getRawSignature()), modifiers(declSpecifier, null));
		if(!returnType.isEmpty()) {
			operation.addParameter(new UMLParameter("return", UMLType.extractTypeObject(returnType), "return", false));
		}
	}

	private void addParameters(UMLOperation operation, IASTFunctionDeclarator declarator, String sourceFolder, String filePath, String fileContent) {
		if(declarator instanceof IASTStandardFunctionDeclarator standardFunctionDeclarator) {
			for(IASTParameterDeclaration parameter : standardFunctionDeclarator.getParameters()) {
				String parameterName = parameter.getDeclarator() != null ? parameter.getDeclarator().getName().toString() : "";
				String parameterType = parameterType(parameter);
				UMLType type = UMLType.extractTypeObject(parameterType);
				UMLParameter umlParameter = new UMLParameter(parameterName, type, "in", false);
				umlParameter.setVariableDeclaration(new VariableDeclaration(sourceFolder, filePath, parameter, type, false, fileContent));
				operation.addParameter(umlParameter);
			}
		}
	}

	private String parameterType(IASTParameterDeclaration parameter) {
		String raw = oneLine(parameter.getRawSignature());
		String name = parameter.getDeclarator() != null ? parameter.getDeclarator().getName().toString() : "";
		if(!name.isBlank() && raw.endsWith(name)) {
			return raw.substring(0, raw.length() - name.length()).trim();
		}
		return oneLine(parameter.getDeclSpecifier().getRawSignature());
	}

	private void addOrReplaceOperation(UMLClass umlClass, UMLOperation operation) {
		UMLOperation existing = findOperation(umlClass, operation.getName(), operation.getParametersWithoutReturnType().size());
		if(existing == null) {
			umlClass.addOperation(operation);
		}
		else if(existing.getActualSignature() == null || !operation.getActualSignature().endsWith(";")) {
			existing.setActualSignature(operation.getActualSignature());
		}
	}

	private UMLOperation findOperation(UMLClass umlClass, String name, int parameterCount) {
		for(UMLOperation operation : umlClass.getOperations()) {
			if(operation.getName().equals(name) && operation.getParametersWithoutReturnType().size() == parameterCount) {
				return operation;
			}
		}
		return null;
	}

	private void printCppUmlSummary() {
		System.out.println("C++ UML summary:");
		for(UMLClass umlClass : cppClassMap.values()) {
			System.out.println("  class " + umlClass.getName());
			for(UMLAttribute attribute : umlClass.getAttributes()) {
				System.out.println("    attribute " + attribute.getVisibility() + " " + staticPrefix(attribute.isStatic()) +
						attribute.getType() + " " + attribute.getName());
			}
			for(UMLOperation operation : umlClass.getOperations()) {
				System.out.println("    operation " + operation.getVisibility() + " " + staticPrefix(operation.isStatic()) +
						constructorPrefix(operation) + operation.getName() + "(" + operationParameters(operation) + ")" +
						returnSuffix(operation));
			}
		}
		System.out.println("---");
	}

	private String staticPrefix(boolean isStatic) {
		return isStatic ? "static " : "";
	}

	private String constructorPrefix(UMLOperation operation) {
		return operation.isConstructor() ? "constructor " : "";
	}

	private String operationParameters(UMLOperation operation) {
		StringJoiner joiner = new StringJoiner(", ");
		for(UMLParameter parameter : operation.getParameters()) {
			if(!parameter.getKind().equals("return")) {
				joiner.add(parameter.getType() + " " + parameter.getName());
			}
		}
		return joiner.toString();
	}

	private String returnSuffix(UMLOperation operation) {
		for(UMLParameter parameter : operation.getParameters()) {
			if(parameter.getKind().equals("return")) {
				return " -> " + parameter.getType();
			}
		}
		return "";
	}

	private void processDeclaration(IASTDeclaration declaration, String indent) {
		System.out.println(indent + "Declaration class: " + declaration.getClass().getName());
		System.out.println(indent + "Raw signature: " + declaration.getRawSignature());
		if(declaration instanceof ICPPASTNamespaceDefinition namespaceDefinition) {
			System.out.println(indent + "Namespace name: " + namespaceDefinition.getName().toString());
			for(IASTDeclaration nestedDeclaration : namespaceDefinition.getDeclarations()) {
				processDeclaration(nestedDeclaration, indent + "  ");
			}
		}
		else if(declaration instanceof IASTSimpleDeclaration simpleDeclaration) {
			IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
			System.out.println(indent + "Decl specifier class: " + declSpecifier.getClass().getName());
			System.out.println(indent + "Decl specifier raw: " + declSpecifier.getRawSignature());
			if(declSpecifier instanceof ICPPASTCompositeTypeSpecifier compositeType) {
				System.out.println(indent + "Composite type name: " + compositeType.getName().toString());
				System.out.println(indent + "Composite type key: " + compositeType.getKey());
				for(IASTDeclaration member : compositeType.getMembers()) {
					System.out.println(indent + "  Member class: " + member.getClass().getName());
					System.out.println(indent + "  Member raw: " + member.getRawSignature());
					System.out.println(indent + "  ---");
				}
			}
		}
		System.out.println(indent + "---");
		// TODO: Map CDT declarations to UMLClass, UMLAttribute, and UMLOperation instances.
	}

	private void printAstSummary(String filePath, IASTTranslationUnit translationUnit) {
		System.out.println("AST summary:");
		System.out.println(fileName(filePath));
		IASTPreprocessorIncludeStatement[] includes = translationUnit.getIncludeDirectives();
		IASTDeclaration[] declarations = translationUnit.getDeclarations();
		int totalItems = includes.length + declarations.length;
		int itemIndex = 0;
		for(IASTPreprocessorIncludeStatement include : includes) {
			printIncludeSummary(include, "", itemIndex == totalItems - 1);
			itemIndex++;
		}
		for(IASTDeclaration declaration : declarations) {
			printDeclarationSummary(declaration, "", itemIndex == totalItems - 1, false, null);
			itemIndex++;
		}
		System.out.println("---");
	}

	private void printIncludeSummary(IASTPreprocessorIncludeStatement include, String prefix, boolean isLast) {
		String connector = isLast ? "└── " : "├── ";
		String includeKind = include.isSystemInclude() ? "system include " : "include ";
		System.out.println(prefix + connector + includeKind + include.getName().toString());
	}

	private void printDeclarationSummary(IASTDeclaration declaration, String prefix, boolean isLast, boolean insideComposite, String compositeName) {
		String connector = isLast ? "└── " : "├── ";
		String childPrefix = prefix + (isLast ? "    " : "│   ");
		System.out.println(prefix + connector + declarationSummary(declaration, insideComposite, compositeName));

		if(declaration instanceof ICPPASTNamespaceDefinition namespaceDefinition) {
			IASTDeclaration[] nestedDeclarations = namespaceDefinition.getDeclarations();
			for(int i = 0; i < nestedDeclarations.length; i++) {
				printDeclarationSummary(nestedDeclarations[i], childPrefix, i == nestedDeclarations.length - 1, false, null);
			}
		}
		else if(declaration instanceof IASTSimpleDeclaration simpleDeclaration) {
			IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
			if(declSpecifier instanceof ICPPASTCompositeTypeSpecifier compositeType) {
				String childCompositeName = compositeType.getName().toString();
				ICPPASTBaseSpecifier[] baseSpecifiers = compositeType.getBaseSpecifiers();
				IASTDeclaration[] members = compositeType.getMembers();
				int totalChildren = baseSpecifiers.length + members.length;
				int childIndex = 0;
				for(ICPPASTBaseSpecifier baseSpecifier : baseSpecifiers) {
					printBaseSpecifierSummary(baseSpecifier, childPrefix, childIndex == totalChildren - 1);
					childIndex++;
				}
				for(IASTDeclaration member : members) {
					printDeclarationSummary(member, childPrefix, childIndex == totalChildren - 1, true, childCompositeName);
					childIndex++;
				}
			}
			else if(declSpecifier instanceof IASTEnumerationSpecifier enumSpecifier) {
				IASTEnumerationSpecifier.IASTEnumerator[] enumerators = enumSpecifier.getEnumerators();
				for(int i = 0; i < enumerators.length; i++) {
					String enumConnector = i == enumerators.length - 1 ? "└── " : "├── ";
					System.out.println(childPrefix + enumConnector + "enum value " + enumerators[i].getName().toString());
				}
			}
		}
	}

	private void printBaseSpecifierSummary(ICPPASTBaseSpecifier baseSpecifier, String prefix, boolean isLast) {
		String connector = isLast ? "└── " : "├── ";
		String virtualPrefix = baseSpecifier.isVirtual() ? "virtual " : "";
		System.out.println(prefix + connector + "base " + virtualPrefix + baseVisibility(baseSpecifier.getVisibility()) + " " + baseSpecifier.getName().toString());
	}

	private String declarationSummary(IASTDeclaration declaration, boolean insideComposite, String compositeName) {
		if(declaration instanceof ICPPASTNamespaceDefinition namespaceDefinition) {
			return "namespace " + namespaceDefinition.getName().toString();
		}
		if(declaration instanceof ICPPASTVisibilityLabel visibilityLabel) {
			return "visibility " + visibilityLabel.getRawSignature().replace(":", "");
		}
		if(declaration instanceof IASTFunctionDefinition functionDefinition) {
			String name = functionName(functionDefinition.getDeclarator());
			String kind = functionKind(name, compositeName, insideComposite, true);
			return kind + functionSignature(functionDefinition.getDeclSpecifier(), functionDefinition.getDeclarator());
		}
		if(declaration instanceof IASTSimpleDeclaration simpleDeclaration) {
			IASTDeclSpecifier declSpecifier = simpleDeclaration.getDeclSpecifier();
			if(declSpecifier instanceof ICPPASTCompositeTypeSpecifier compositeType) {
				return compositeTypeKind(compositeType) + " " + compositeType.getName().toString();
			}
			if(declSpecifier instanceof IASTEnumerationSpecifier enumSpecifier) {
				return "enum " + enumSpecifier.getName().toString();
			}
			if(hasFunctionDeclarator(simpleDeclaration)) {
				return functionSignatures(declSpecifier, simpleDeclaration.getDeclarators(), insideComposite, compositeName, false);
			}
			if(insideComposite) {
				return "field " + fieldSignatures(declSpecifier, simpleDeclaration.getDeclarators());
			}
			return "declaration " + oneLine(declaration.getRawSignature());
		}
		return oneLine(declaration.getRawSignature());
	}

	private boolean hasFunctionDeclarator(IASTSimpleDeclaration simpleDeclaration) {
		for(IASTDeclarator declarator : simpleDeclaration.getDeclarators()) {
			if(declarator instanceof IASTFunctionDeclarator) {
				return true;
			}
		}
		return false;
	}

	private String functionSignatures(IASTDeclSpecifier declSpecifier, IASTDeclarator[] declarators,
			boolean insideComposite, String compositeName, boolean definition) {
		StringJoiner joiner = new StringJoiner(", ");
		for(IASTDeclarator declarator : declarators) {
			if(declarator instanceof IASTFunctionDeclarator functionDeclarator) {
				joiner.add(functionKind(functionName(functionDeclarator), compositeName, insideComposite, definition) +
						functionSignature(declSpecifier, functionDeclarator));
			}
			else {
				joiner.add(oneLine(declarator.getRawSignature()));
			}
		}
		return joiner.length() == 0 ? "<anonymous>" : joiner.toString();
	}

	private String functionSignature(IASTDeclSpecifier declSpecifier, IASTFunctionDeclarator declarator) {
		StringBuilder sb = new StringBuilder();
		String modifiers = modifiers(declSpecifier, declarator);
		if(!modifiers.isEmpty()) {
			sb.append(modifiers).append(" ");
		}
		String returnType = stripLeadingKeywords(oneLine(declSpecifier.getRawSignature()), modifiers);
		if(!returnType.isEmpty()) {
			sb.append(returnType).append(" ");
		}
		sb.append(functionName(declarator)).append("(").append(parameterSignatures(declarator)).append(")");
		if(declarator instanceof ICPPASTFunctionDeclarator cppDeclarator) {
			if(cppDeclarator.isConst()) {
				sb.append(" const");
			}
			if(cppDeclarator.isOverride()) {
				sb.append(" override");
			}
			if(cppDeclarator.isFinal()) {
				sb.append(" final");
			}
			if(cppDeclarator.isPureVirtual()) {
				sb.append(" = 0");
			}
		}
		return sb.toString();
	}

	private String parameterSignatures(IASTFunctionDeclarator declarator) {
		if(declarator instanceof IASTStandardFunctionDeclarator standardFunctionDeclarator) {
			StringJoiner joiner = new StringJoiner(", ");
			for(IASTParameterDeclaration parameter : standardFunctionDeclarator.getParameters()) {
				joiner.add(parameterSignature(parameter));
			}
			if(standardFunctionDeclarator.takesVarArgs()) {
				joiner.add("...");
			}
			return joiner.toString();
		}
		return "";
	}

	private String parameterSignature(IASTParameterDeclaration parameter) {
		return oneLine(parameter.getRawSignature());
	}

	private String fieldSignatures(IASTDeclSpecifier declSpecifier, IASTDeclarator[] declarators) {
		StringJoiner joiner = new StringJoiner(", ");
		String type = oneLine(declSpecifier.getRawSignature());
		String modifiers = modifiers(declSpecifier, null);
		type = stripLeadingKeywords(type, modifiers);
		for(IASTDeclarator declarator : declarators) {
			String name = declarator.getName().toString();
			StringBuilder sb = new StringBuilder();
			if(!modifiers.isEmpty()) {
				sb.append(modifiers).append(" ");
			}
			if(!type.isEmpty()) {
				sb.append(type).append(" ");
			}
			sb.append(name.isBlank() ? oneLine(declarator.getRawSignature()) : name);
			joiner.add(sb.toString());
		}
		return joiner.length() == 0 ? "<anonymous>" : joiner.toString();
	}

	private String declaratorNames(IASTDeclarator[] declarators) {
		StringJoiner joiner = new StringJoiner(", ");
		for(IASTDeclarator declarator : declarators) {
			String name = declarator.getName().toString();
			joiner.add(name.isBlank() ? oneLine(declarator.getRawSignature()) : name);
		}
		return joiner.length() == 0 ? "<anonymous>" : joiner.toString();
	}

	private String functionName(IASTDeclarator declarator) {
		String name = declarator.getName().toString();
		return name.isBlank() ? oneLine(declarator.getRawSignature()) : name;
	}

	private String compositeTypeKind(ICPPASTCompositeTypeSpecifier compositeType) {
		return switch(compositeType.getKey()) {
			case IASTCompositeTypeSpecifier.k_struct -> "struct";
			case IASTCompositeTypeSpecifier.k_union -> "union";
			case ICPPASTCompositeTypeSpecifier.k_class -> "class";
			default -> "composite";
		};
	}

	private String modifiers(IASTDeclSpecifier declSpecifier, IASTFunctionDeclarator declarator) {
		StringJoiner joiner = new StringJoiner(" ");
		switch(declSpecifier.getStorageClass()) {
			case IASTDeclSpecifier.sc_static -> joiner.add("static");
			case IASTDeclSpecifier.sc_extern -> joiner.add("extern");
			case IASTDeclSpecifier.sc_typedef -> joiner.add("typedef");
			case IASTDeclSpecifier.sc_mutable -> joiner.add("mutable");
			default -> {
			}
		}
		if(declSpecifier.isInline()) {
			joiner.add("inline");
		}
		if(declSpecifier instanceof ICPPASTDeclSpecifier cppDeclSpecifier) {
			if(cppDeclSpecifier.isExplicit()) {
				joiner.add("explicit");
			}
			if(cppDeclSpecifier.isVirtual()) {
				joiner.add("virtual");
			}
			if(cppDeclSpecifier.isConstexpr()) {
				joiner.add("constexpr");
			}
			if(cppDeclSpecifier.isFriend()) {
				joiner.add("friend");
			}
			if(cppDeclSpecifier.isThreadLocal()) {
				joiner.add("thread_local");
			}
		}
		if(declarator instanceof ICPPASTFunctionDeclarator cppDeclarator && cppDeclarator.isPureVirtual()) {
			joiner.add("abstract");
		}
		return joiner.toString();
	}

	private String functionKind(String name, String compositeName, boolean insideComposite, boolean definition) {
		String suffix = definition ? " definition " : " declaration ";
		String simpleName = simpleFunctionName(name);
		if(insideComposite && compositeName != null) {
			if(simpleName.equals(compositeName)) {
				return "constructor" + suffix;
			}
			if(simpleName.equals("~" + compositeName)) {
				return "destructor" + suffix;
			}
			return "method" + suffix;
		}
		if(name.contains("::")) {
			String owner = name.substring(0, name.lastIndexOf("::"));
			String ownerSimpleName = simpleFunctionName(owner);
			if(simpleName.equals(ownerSimpleName)) {
				return "out-of-class constructor" + suffix;
			}
			if(simpleName.equals("~" + ownerSimpleName)) {
				return "out-of-class destructor" + suffix;
			}
			return "out-of-class method" + suffix;
		}
		return "function" + suffix;
	}

	private String simpleFunctionName(String name) {
		int index = name.lastIndexOf("::");
		return index == -1 ? name : name.substring(index + 2);
	}

	private String stripLeadingKeywords(String text, String modifiers) {
		if(text.isEmpty() || modifiers.isEmpty()) {
			return text;
		}
		String result = text;
		String[] keywords = {"static", "extern", "typedef", "mutable", "inline", "explicit", "virtual", "constexpr", "friend", "thread_local"};
		boolean changed;
		do {
			changed = false;
			for(String keyword : keywords) {
				if(modifiers.contains(keyword) && result.equals(keyword)) {
					return "";
				}
				if(modifiers.contains(keyword) && result.startsWith(keyword + " ")) {
					result = result.substring(keyword.length()).trim();
					changed = true;
				}
			}
		} while(changed);
		return result;
	}

	private String baseVisibility(int visibility) {
		return switch(visibility) {
			case ICPPASTBaseSpecifier.v_public -> "public";
			case ICPPASTBaseSpecifier.v_protected -> "protected";
			case ICPPASTBaseSpecifier.v_private -> "private";
			default -> "unspecified";
		};
	}

	private Visibility visibility(int cppVisibility, Visibility fallback) {
		return switch(cppVisibility) {
			case ICPPASTVisibilityLabel.v_public -> Visibility.PUBLIC;
			case ICPPASTVisibilityLabel.v_protected -> Visibility.PROTECTED;
			case ICPPASTVisibilityLabel.v_private -> Visibility.PRIVATE;
			default -> fallback;
		};
	}

	private LocationInfo cppLocation(String sourceFolder, String filePath, IASTNode node,
			LocationInfo.CodeElementType codeElementType, String fileContent) {
		return new LocationInfo(sourceFolder, filePath, node, codeElementType, fileContent);
	}

	private String qualifiedClassName(String namespace, String className) {
		return namespace == null || namespace.isEmpty() ? className : namespace + "." + className;
	}

	private String qualifyCppName(String namespace, String name) {
		if(name.contains("::")) {
			return name.replace("::", ".");
		}
		return qualifiedClassName(namespace, name);
	}

	private String ownerName(String qualifiedName) {
		int index = qualifiedName.lastIndexOf("::");
		if(index == -1) {
			return null;
		}
		String owner = qualifiedName.substring(0, index);
		return owner.substring(owner.lastIndexOf("::") + 2);
	}

	private String oneLine(String text) {
		return text.replace('\n', ' ').replaceAll("\\s+", " ").trim();
	}

	private String fileName(String filePath) {
		int index = Math.max(filePath.lastIndexOf('/'), filePath.lastIndexOf('\\'));
		return index == -1 ? filePath : filePath.substring(index + 1);
	}

}
