
update refactoringgit set description = 'Extract Method private createBuckFiles(buckFilesData Map<Path,SortedSet<Prebuilt>>) : void extracted from public resolve(mavenCoords String[]) : void in class com.facebook.buck.maven.Resolver' where description = 'Extract Method private createBuckFiles(buckFilesData Map<Path,SortedSet<Prebuilt>>) : void extracted from public resolve(mavenCoords String) : void in class com.facebook.buck.maven.Resolver';
update refactoringgit set description = 'Extract Method private downloadArtifact(artifactToDownload Artifact, repoSys RepositorySystem, session RepositorySystemSession, buckFiles Map<Path,SortedSet<Prebuilt>>, graph MutableDirectedGraph<Artifact>) : void extracted from public resolve(mavenCoords String[]) : void in class com.facebook.buck.maven.Resolver' where description = 'Extract Method  private downloadArtifact(artifactToDownload Artifact, repoSys RepositorySystem, session RepositorySystemSession, buckFiles Map<Path,SortedSet<Prebuilt>>, graph MutableDirectedGraph<Artifact>) : void extracted from public resolve(mavenCoords String) : void in class com.facebook.buck.maven.Resolver';
update refactoringgit set description = 'Extract Method public instantiateObject(className String, args Object[]) : Object extracted from public instantiateObject(className String) : Object in class org.drools.core.util.ClassUtils' where description = 'Extract Method public instantiateObject(className String, args Object) : Object extracted from public instantiateObject(className String) : Object in class org.drools.core.util.ClassUtils';
update refactoringgit set description = 'Move Method  protected logWarn(message String, arguments Object[]) : void from class cascading.stats.tez.TezNodeStats to protected logWarn(message String, arguments Object[]) : void from class cascading.stats.CascadingStats' where description = 'Move Method  protected logWarn(message String, arguments Object) : void from class cascading.stats.tez.TezNodeStats to protected logWarn(message String, arguments Object) : void from class cascading.stats.CascadingStats';
update refactoringgit set description = 'Move Method  protected logDebug(message String, arguments Object[]) : void from class cascading.stats.tez.TezNodeStats to protected logDebug(message String, arguments Object[]) : void from class cascading.stats.CascadingStats' where description = 'Move Method  protected logDebug(message String, arguments Object) : void from class cascading.stats.tez.TezNodeStats to protected logDebug(message String, arguments Object) : void from class cascading.stats.CascadingStats';
update refactoringgit set description = 'Move Method  protected logInfo(message String, arguments Object[]) : void from class cascading.stats.tez.TezNodeStats to protected logInfo(message String, arguments Object[]) : void from class cascading.stats.CascadingStats' where description = 'Move Method  protected logInfo(message String, arguments Object) : void from class cascading.stats.tez.TezNodeStats to protected logInfo(message String, arguments Object) : void from class cascading.stats.CascadingStats';
update refactoringgit set description = 'Extract Method private load(config Class<?>, environment String[]) : void extracted from public overrideMessageCodesFormat() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests' where description = 'Extract Method  private load(config Class<?>, environment String) : void extracted from public overrideMessageCodesFormat() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests';
update refactoringgit set description = 'Extract Method private load(config Class<?>, environment String[]) : void extracted from public overrideDateFormat() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests' where description = 'Extract Method  private load(config Class<?>, environment String) : void extracted from public overrideDateFormat() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests';
update refactoringgit set description = 'Extract Method private load(config Class<?>, environment String[]) : void extracted from public overrideLocale() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests' where description = 'Extract Method  private load(config Class<?>, environment String) : void extracted from public overrideLocale() : void in class org.springframework.boot.autoconfigure.web.WebMvcAutoConfigurationTests';
update refactoringgit set description = 'Extract Method private getBlogsForCurrentView() : List<Map<String,Object>> extracted from protected doInBackground(params Void[]) : SiteList in class org.wordpress.android.ui.main.SitePickerAdapter.LoadSitesTask' where description = 'Extract Method private getBlogsForCurrentView() : List<Map<String,Object>> extracted from protected doInBackground(params Void) : SiteList in class org.wordpress.android.ui.main.SitePickerAdapter.LoadSitesTask';
update refactoringgit set description = 'Extract Method public deleteRowAt(metadata CFMetaData, timestamp long, localDeletionTime int, key Object, clusteringValues Object[]) : Mutation extracted from public deleteRow(metadata CFMetaData, timestamp long, key Object, clusteringValues Object[]) : Mutation in class org.apache.cassandra.db.RowUpdateBuilder' where description = 'Extract Method  public deleteRowAt(metadata CFMetaData, timestamp long, localDeletionTime int, key Object, clusteringValues Object) : Mutation extracted from public deleteRow(metadata CFMetaData, timestamp long, key Object, clusteringValues Object) : Mutation in class org.apache.cassandra.db.RowUpdateBuilder';
update refactoringgit set description = 'Extract Method public execMultiLineCommands(db ODatabaseRecordTx, log boolean, stopOnException boolean, commands String[]) : void extracted from public execMultiLineCommands(db ODatabaseRecordTx, log boolean, commands String[]) : void in class com.baasbox.db.DbHelper' where description = 'Extract Method public execMultiLineCommands(db ODatabaseRecordTx, log boolean, stopOnException boolean, commands String) : void extracted from public execMultiLineCommands(db ODatabaseRecordTx, log boolean, commands String) : void in class com.baasbox.db.DbHelper';
update refactoringgit set description = 'Extract Method public readCharacter(checkForAltKeyCombo boolean, allowed char[]) : int extracted from public readCharacter(allowed char[]) : int in class jline.console.ConsoleReader' where description = 'Extract Method public readCharacter(checkForAltKeyCombo boolean, allowed char) : int extracted from public readCharacter(allowed char) : int in class jline.console.ConsoleReader';
update refactoringgit set description = 'Extract Method public addQueueItem(context Context, performAutoDownload boolean, itemIds long[]) : Future<?> extracted from public addQueueItem(context Context, itemIds long[]) : Future<?> in class de.danoeh.antennapod.core.storage.DBWriter' where description = 'Extract Method  public addQueueItem(context Context, performAutoDownload boolean, itemIds long) : Future<?> extracted from public addQueueItem(context Context, itemIds long) : Future<?> in class de.danoeh.antennapod.core.storage.DBWriter';
update refactoringgit set description = 'Extract Method protected assertInvalidThrowMessage(errorMessage String, exception Class<? extends Throwable>, query String, values Object[]) : void extracted from protected assertInvalidMessage(errorMessage String, query String, values Object[]) : void in class org.apache.cassandra.cql3.CQLTester' where description = 'Extract Method protected assertInvalidThrowMessage(errorMessage String, exception Class<? extends Throwable>, query String, values Object) : void extracted from protected assertInvalidMessage(errorMessage String, query String, values Object) : void in class org.apache.cassandra.cql3.CQLTester';
update refactoringgit set description = 'Extract Method private hepPlan(basePlan RelNode, followPlanChanges boolean, mdProvider RelMetadataProvider, order HepMatchOrder, rules RelOptRule[]) : RelNode extracted from private hepPlan(basePlan RelNode, followPlanChanges boolean, mdProvider RelMetadataProvider, rules RelOptRule[]) : RelNode in class org.apache.hadoop.hive.ql.parse.CalcitePlanner.CalcitePlannerAction' where description = 'Extract Method private hepPlan(basePlan RelNode, followPlanChanges boolean, mdProvider RelMetadataProvider, order HepMatchOrder, rules RelOptRule) : RelNode extracted from private hepPlan(basePlan RelNode, followPlanChanges boolean, mdProvider RelMetadataProvider, rules RelOptRule) : RelNode in class org.apache.hadoop.hive.ql.parse.CalcitePlanner.CalcitePlannerAction';

UPDATE refactoringgit SET description='Extract Method  package getPreparedQuery(type QueryType, columns Set<ColumnMapper<?>>, options Option[]) : PreparedStatement extracted from package getPreparedQuery(type QueryType, options Option[]) : PreparedStatement in class com.datastax.driver.mapping.Mapper' WHERE `id`='891149';
