create table weeks (
  id int auto_increment primary key, 
  start date
);

insert into weeks (start) values ('2015-03-22');

insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;
insert into weeks (start) select DATE_SUB(min(start), INTERVAL 7 DAY) from weeks;

select * from weeks;