package jetbrains.mps.lang.textGen.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 4:
        return new ConceptTextGenDeclaration_BehaviorDescriptor();
      case 19:
        return new NodeParameter_BehaviorDescriptor();
      case 13:
        return new GenerateTextDeclaration_BehaviorDescriptor();
      case 14:
        return new IncreaseDepthOperation_BehaviorDescriptor();
      case 7:
        return new DecreaseDepthOperation_BehaviorDescriptor();
      case 15:
        return new IndentBufferOperation_BehaviorDescriptor();
      case 16:
        return new LanguageTextGenDeclaration_BehaviorDescriptor();
      case 21:
        return new OperationDeclaration_BehaviorDescriptor();
      case 20:
        return new OperationCall_BehaviorDescriptor();
      case 6:
        return new ContextParameter_BehaviorDescriptor();
      case 2:
        return new BufferParameter_BehaviorDescriptor();
      case 25:
        return new UtilityMethodDeclaration_BehaviorDescriptor();
      case 24:
        return new UtilityMethodCall_BehaviorDescriptor();
      case 12:
        return new FoundErrorOperation_BehaviorDescriptor();
      case 26:
        return new WithIndentOperation_BehaviorDescriptor();
      case 17:
        return new NewLineAppendPart_BehaviorDescriptor();
      case 18:
        return new NodeAppendPart_BehaviorDescriptor();
      case 3:
        return new CollectionAppendPart_BehaviorDescriptor();
      case 5:
        return new ConstantStringAppendPart_BehaviorDescriptor();
      case 0:
        return new AppendOperation_BehaviorDescriptor();
      case 10:
        return new ExtensionDeclaration_BehaviorDescriptor();
      case 22:
        return new ReferenceAppendPart_BehaviorDescriptor();
      case 9:
        return new EncodingLiteral_BehaviorDescriptor();
      case 8:
        return new EncodingDeclaration_BehaviorDescriptor();
      case 11:
        return new FilenameFunction_BehaviorDescriptor();
      case 23:
        return new StubOperationDeclaration_BehaviorDescriptor();
      case 1:
        return new AttributedNodePart_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"jetbrains.mps.lang.textGen.structure.AppendOperation", "jetbrains.mps.lang.textGen.structure.AttributedNodePart", "jetbrains.mps.lang.textGen.structure.BufferParameter", "jetbrains.mps.lang.textGen.structure.CollectionAppendPart", "jetbrains.mps.lang.textGen.structure.ConceptTextGenDeclaration", "jetbrains.mps.lang.textGen.structure.ConstantStringAppendPart", "jetbrains.mps.lang.textGen.structure.ContextParameter", "jetbrains.mps.lang.textGen.structure.DecreaseDepthOperation", "jetbrains.mps.lang.textGen.structure.EncodingDeclaration", "jetbrains.mps.lang.textGen.structure.EncodingLiteral", "jetbrains.mps.lang.textGen.structure.ExtensionDeclaration", "jetbrains.mps.lang.textGen.structure.FilenameFunction", "jetbrains.mps.lang.textGen.structure.FoundErrorOperation", "jetbrains.mps.lang.textGen.structure.GenerateTextDeclaration", "jetbrains.mps.lang.textGen.structure.IncreaseDepthOperation", "jetbrains.mps.lang.textGen.structure.IndentBufferOperation", "jetbrains.mps.lang.textGen.structure.LanguageTextGenDeclaration", "jetbrains.mps.lang.textGen.structure.NewLineAppendPart", "jetbrains.mps.lang.textGen.structure.NodeAppendPart", "jetbrains.mps.lang.textGen.structure.NodeParameter", "jetbrains.mps.lang.textGen.structure.OperationCall", "jetbrains.mps.lang.textGen.structure.OperationDeclaration", "jetbrains.mps.lang.textGen.structure.ReferenceAppendPart", "jetbrains.mps.lang.textGen.structure.StubOperationDeclaration", "jetbrains.mps.lang.textGen.structure.UtilityMethodCall", "jetbrains.mps.lang.textGen.structure.UtilityMethodDeclaration", "jetbrains.mps.lang.textGen.structure.WithIndentOperation"};
}
