package jetbrains.mps.editor.runtime.impl.cellActions;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.selection.Selection;
import jetbrains.mps.openapi.editor.selection.SingularSelection;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.nodeEditor.selection.EditorCellLabelSelection;

public class CellAction_Comment extends AbstractCellAction {
  private final SNode myNode;
  private SNode myParent;

  public CellAction_Comment(@NotNull SNode node) {
    this.myNode = node;
    this.myParent = SNodeOperations.getParent(myNode);
  }

  @Override
  public boolean canExecute(EditorContext editorContext) {
    Selection selection = editorContext.getSelectionManager().getSelection();
    return this.myParent != null && selection != null && selection instanceof SingularSelection && needToComment(editorContext);
  }

  public void execute(EditorContext editorContext) {
    Selection selection = editorContext.getSelectionManager().getSelection();
    SNode newComment = CommentUtil.commentOut(myNode);
  }
  private boolean needToComment(EditorContext editorContext) {
    boolean needToComment;
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(myNode), MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x3dcc194340c24debL, "jetbrains.mps.lang.core.structure.BaseCommentAttribute"))) {
      needToComment = false;
    } else if ((SNodeOperations.getNodeAncestor(myNode, MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x3dcc194340c24debL, "jetbrains.mps.lang.core.structure.BaseCommentAttribute"), false, false) == null)) {
      needToComment = true;
    } else {
      Selection selection = editorContext.getSelectionManager().getSelection();
      if ((selection instanceof EditorCellLabelSelection && !(((EditorCellLabelSelection) selection).hasNonTrivialSelection()))) {
        needToComment = false;
      } else {
        needToComment = true;
      }
    }
    return needToComment;
  }

}
