package jetbrains.mps.editor.runtime.impl.cellActions;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class Cell_Action_Uncomment extends AbstractCellAction {
  private final SNode myNode;

  public Cell_Action_Uncomment(@NotNull SNode node) {
    this.myNode = node;
  }

  @Override
  public boolean canExecute(EditorContext context) {
    return SNodeOperations.getParent(myNode) != null;
  }

  public void execute(EditorContext editorContext) {
    SNode commentedNode = CommentUtil.uncomment(myNode);
  }

}
