import { StyleSheet } from 'react-native';

export const upcomingClassesSliderStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 8,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 2,
    gap: 10,
  },
  headerDateTimeText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
    flex: 1,
  },
  headerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  card: {
    backgroundColor: 'rgba(99, 24, 39, 0.72)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 36,
    gap: 10,
    alignSelf: 'stretch',
  },
  title: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  eventsViewport: {
    width: '100%',
    minHeight: 0,
    flexShrink: 1,
    overflow: 'hidden',
  },
  eventsList: {
    width: '100%',
    flexGrow: 0,
  },
  eventsContent: {
    gap: 8,
  },
  overflowIndicatorText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 4,
  },
  eventItem: {
    backgroundColor: 'rgba(45, 10, 16, 0.65)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    height: 78,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  eventTextWrap: {
    flex: 1,
    gap: 2,
  },
  eventTitleText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
  },
  eventDateTimeText: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 10.5,
    lineHeight: 13,
    fontWeight: '600',
  },
  eventMetaText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '500',
  },
  infoText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
    textAlign: 'center',
  },
  errorText: {
    color: '#ffd8ab',
    fontSize: 13,
    textAlign: 'center',
  },
  retryButton: {
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  reselectButton: {
    alignSelf: 'stretch',
    marginTop: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  reselectButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
});
